# Generated by Django 5.2.17 on 2026-09-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(db_index=True, max_length=100, verbose_name='仓库标识')),
                ('repo_label', models.CharField(blank=True, max_length=100, verbose_name='展示名称')),
                ('sha', models.CharField(max_length=40, verbose_name='提交 sha')),
                ('short_sha', models.CharField(blank=True, max_length=12, verbose_name='短 sha')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='分支')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('commit_type', models.CharField(blank=True, max_length=20, verbose_name='类型')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('committed_at', models.DateTimeField(db_index=True, verbose_name='提交时间')),
                ('files_changed', models.PositiveIntegerField(default=0, verbose_name='变更文件数')),
                ('insertions', models.PositiveIntegerField(default=0, verbose_name='新增行')),
                ('deletions', models.PositiveIntegerField(default=0, verbose_name='删除行')),
                ('is_private', models.BooleanField(default=False, verbose_name='来自私有仓库')),
                ('is_public', models.BooleanField(default=True, verbose_name='对外展示')),
                ('show_summary', models.BooleanField(default=True, verbose_name='展示摘要文字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '开发提交',
                'verbose_name_plural': '开发提交',
                'ordering': ['-committed_at'],
                'unique_together': {('repo', 'sha')},
            },
        ),
    ]
